"""Add users, words and answer_history

Revision ID: 2a0ed7f1deb4
Revises: 
Create Date: 2020-02-08 22:35:55.512998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0ed7f1deb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('avatar_url', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('repeat', sa.DateTime(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_table('answer_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('word', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['word'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_history_id'), 'answer_history', ['id'], unique=False)
    op.create_table('translates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('word', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=False),
    sa.Column('part_of_speech', sa.Enum('noun', 'verb', 'adjective', 'adverb', 'pronoun', 'preposition', 'conjunction', 'interjection', 'article', 'participle', name='partofspeechenum'), nullable=False),
    sa.ForeignKeyConstraint(['word'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translates_id'), 'translates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translates_id'), table_name='translates')
    op.drop_table('translates')
    op.drop_index(op.f('ix_answer_history_id'), table_name='answer_history')
    op.drop_table('answer_history')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
