"""Add predicative to translates.part_of_speech

Revision ID: 3a447dee97a1
Revises: 2a0ed7f1deb4
Create Date: 2020-02-09 16:23:53.791908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a447dee97a1'
down_revision = '2a0ed7f1deb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
